# Generated by Django 5.1.15 on 2026-04-17 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_contracted_with_organization', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='organizations.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PharmacistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacists', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['organization', 'is_contracted_with_organization'], name='pharmacies__organiz_26a5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['name'], name='pharmacies__name_0048a5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacistprofile',
            index=models.Index(fields=['pharmacy'], name='pharmacies__pharmac_26169e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacistprofile',
            index=models.Index(fields=['is_approved'], name='pharmacies__is_appr_c931f5_idx'),
        ),
    ]
