# Generated by Django 5.1.15 on 2026-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0002_pharmacy_city_pharmacy_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
