# Generated by Django 5.1.15 on 2026-04-17 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='organizatio_name_537540_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('can_manage_patients', models.BooleanField(default=True)),
                ('can_manage_pharmacists', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('organization__name', 'user__email'),
                'indexes': [models.Index(fields=['organization'], name='organizatio_organiz_075d3a_idx'), models.Index(fields=['can_manage_patients', 'can_manage_pharmacists'], name='organizatio_can_man_343316_idx')],
            },
        ),
    ]
