# Generated by Django 5.1.15 on 2026-05-01 17:41

from django.db import migrations, models


def normalize_blank_identifiers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email="").update(email=None)
    User.objects.filter(phone_number="").update(phone_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_staff_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(
            normalize_blank_identifiers,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
