# Generated by Django 5.1.15 on 2026-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_approval_status_user_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("patient_register", "Patient registration"),
                    ("pharmacist_register", "Pharmacist registration"),
                    ("patient_password_reset", "Patient password reset"),
                    ("pharmacist_password_reset", "Pharmacist password reset"),
                ],
                max_length=32,
            ),
        ),
    ]
