# Generated by Django 5.1.15 on 2026-04-17 23:10

import django.db.models.deletion
import django.utils.timezone
import prescriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_specialty', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientprofile')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacies.pharmacistprofile')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacies.pharmacy')),
                ('reused_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_children', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ('-prescribed_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('item_update', 'Item Update'), ('confirm', 'Confirm')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_access_logs', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_image', models.ImageField(blank=True, null=True, upload_to=prescriptions.models.medicine_image_upload_to)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions_audio', models.FileField(blank=True, null=True, upload_to=prescriptions.models.instructions_audio_upload_to)),
                ('instructions_transcript_raw', models.TextField(blank=True)),
                ('instructions_transcript_edited', models.TextField(blank=True)),
                ('sign_language_video', models.FileField(blank=True, null=True, upload_to=prescriptions.models.sign_language_video_upload_to)),
                ('supporting_text', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-prescribed_at'], name='prescriptio_patient_483e54_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['pharmacist', 'status'], name='prescriptio_pharmac_02d9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['pharmacy', 'status'], name='prescriptio_pharmac_270ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionaccesslog',
            index=models.Index(fields=['prescription', 'timestamp'], name='prescriptio_prescri_cafb28_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionaccesslog',
            index=models.Index(fields=['access_type'], name='prescriptio_access__9a9911_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription', 'is_confirmed'], name='prescriptio_prescri_99bd42_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['medicine_name'], name='prescriptio_medicin_b49085_idx'),
        ),
    ]
