# Generated by Django 5.1.15 on 2026-04-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='transcription_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='transcription_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='transcription_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='transcription_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='transcription_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionaccesslog',
            name='access_type',
            field=models.CharField(choices=[('view', 'View'), ('item_update', 'Item Update'), ('confirm', 'Confirm'), ('transcribe', 'Transcribe')], max_length=20),
        ),
    ]
