# Generated by Django 5.1.15 on 2026-05-01 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patientsessionqr_patientsession_expires_at_and_more"),
        ("pharmacies", "0001_initial"),
        ("prescriptions", "0002_prescriptionitem_transcription_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="prescription",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions",
                to="patients.patientsession",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="dosage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="duration",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="frequency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="instructions_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="sign_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("delivered", "Delivered"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["session"], name="prescriptio_session_103533_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["prescription", "sign_status"],
                name="prescriptio_prescri_bde7ef_idx",
            ),
        ),
    ]
