# Generated by Django 5.1.15 on 2026-05-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientmedicalinfo_blood_type'),
        ('prescriptions', '0003_prescription_diagnosis_prescription_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('approved_instruction_text', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('sign_unclear', 'Sign unclear')], default='sign_unclear', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_quality_reports', to='patients.patientprofile')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_quality_reports', to='prescriptions.prescription')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_quality_reports', to='prescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['patient', 'status'], name='prescriptio_patient_26ccc6_idx'), models.Index(fields=['prescription', 'status'], name='prescriptio_prescri_fd4b3e_idx'), models.Index(fields=['prescription_item', 'report_type', 'status'], name='prescriptio_prescri_b0ca93_idx'), models.Index(fields=['report_type', 'status'], name='prescriptio_report__fc28a5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('patient', 'prescription_item', 'report_type'), name='unique_open_sign_quality_report')],
            },
        ),
    ]
