# Generated by Django 5.1.15 on 2026-05-13 23:02

from decimal import Decimal

from django.db import migrations, models

MONEY_QUANTUM = Decimal("0.01")


def backfill_pricing_fields(apps, schema_editor):
    Prescription = apps.get_model("prescriptions", "Prescription")
    PrescriptionItem = apps.get_model("prescriptions", "PrescriptionItem")

    for item in PrescriptionItem.objects.all().iterator():
        quantity = item.quantity if item.quantity is not None else Decimal("1.00")
        item.unit_price = item.price or Decimal("0.00")
        item.quantity = quantity
        item.line_total = (item.unit_price * quantity).quantize(MONEY_QUANTUM)
        item.save(update_fields=["unit_price", "quantity", "line_total"])

    for prescription in Prescription.objects.all().iterator():
        total = sum(
            PrescriptionItem.objects.filter(prescription_id=prescription.id).values_list(
                "line_total",
                flat=True,
            ),
            Decimal("0.00"),
        )
        prescription.total_price = total.quantize(MONEY_QUANTUM)
        prescription.save(update_fields=["total_price"])


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_signqualityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='currency',
            field=models.CharField(default='SYP', max_length=3),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_pricing_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
