# Generated by Django 5.1.15 on 2026-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_signqualityreport_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='pose_file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='pose_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='pose_shape',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
