# Generated by Django 5.1.15 on 2026-06-05 09:28

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescriptionitem_ai_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=common.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions_text',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions_transcript_edited',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions_transcript_raw',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='supporting_text',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signqualityreport',
            name='approved_instruction_text',
            field=common.fields.EncryptedTextField(blank=True),
        ),
    ]
