# Generated by Django 5.1.15 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0008_alter_prescription_diagnosis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="avatar_video_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="generated_video_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="generated_video_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="generation_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="generation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="sign_error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
