# Generated by Django 5.1.15 on 2026-06-05

from django.db import migrations


def _encrypt_existing_values(model, fields):
    for obj in model.objects.all().iterator():
        values = {field: getattr(obj, field) for field in fields if getattr(obj, field)}
        if values:
            model.objects.filter(pk=obj.pk).update(**values)


def encrypt_existing_prescription_medical_text(apps, schema_editor):
    Prescription = apps.get_model("prescriptions", "Prescription")
    PrescriptionItem = apps.get_model("prescriptions", "PrescriptionItem")
    SignQualityReport = apps.get_model("prescriptions", "SignQualityReport")

    _encrypt_existing_values(Prescription, ("diagnosis", "notes"))
    _encrypt_existing_values(
        PrescriptionItem,
        (
            "instructions_text",
            "instructions_transcript_raw",
            "instructions_transcript_edited",
            "supporting_text",
        ),
    )
    _encrypt_existing_values(SignQualityReport, ("approved_instruction_text",))


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0009_prescriptionitem_sign_generation_outputs"),
    ]

    operations = [
        migrations.RunPython(
            encrypt_existing_prescription_medical_text,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
