# Generated by Django 5.1.15 on 2026-04-17 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('hearing_disability_level', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('profound', 'Profound')], max_length=20)),
                ('is_self_registered', models.BooleanField(default=False)),
                ('qr_code_value', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('qr_is_active', models.BooleanField(default=False)),
                ('record_access_pin_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('is_pregnant', models.BooleanField(blank=True, null=True)),
                ('is_breastfeeding', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient medical info',
                'verbose_name_plural': 'Patient medical info',
            },
        ),
        migrations.CreateModel(
            name='PatientEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('hearing_disability_level', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('profound', 'Profound')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_account_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_enrollments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.organization')),
                ('patient_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_record', to='patients.patientprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['organization'], name='patients_pa_organiz_28157b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['full_name'], name='patients_pa_full_na_05d11e_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['qr_is_active'], name='patients_pa_qr_is_a_8086a4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientenrollment',
            index=models.Index(fields=['organization', 'last_name', 'birth_date'], name='patients_pa_organiz_912fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientenrollment',
            index=models.Index(fields=['phone_number'], name='patients_pa_phone_n_b180fd_idx'),
        ),
        migrations.AddIndex(
            model_name='patientenrollment',
            index=models.Index(fields=['is_account_created'], name='patients_pa_is_acco_639067_idx'),
        ),
    ]
