# Generated by Django 5.1.15 on 2026-04-17 23:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.CharField(choices=[('qr_scan', 'QR Scan'), ('login', 'Patient Login')], default='qr_scan', max_length=20)),
                ('qr_code_value_snapshot', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patientprofile')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to='pharmacies.pharmacistprofile')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ('-started_at', '-created_at'),
                'indexes': [models.Index(fields=['patient', '-started_at'], name='patients_pa_patient_738586_idx'), models.Index(fields=['pharmacist', '-started_at'], name='patients_pa_pharmac_3590c4_idx'), models.Index(fields=['pharmacy', '-started_at'], name='patients_pa_pharmac_ffe324_idx'), models.Index(fields=['access_type'], name='patients_pa_access__3f5049_idx')],
            },
        ),
    ]
