# Generated by Django 5.1.15 on 2026-05-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("prescription_reminders", models.BooleanField(default=True)),
                ("dark_mode", models.BooleanField(default=False)),
                ("use_biometrics", models.BooleanField(default=False)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient settings",
                "verbose_name_plural": "Patient settings",
            },
        ),
    ]
