# Generated by Django 5.1.15 on 2026-05-01 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patientsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientLoginQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patient_login_qrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_qr_tokens",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient login QR",
                "verbose_name_plural": "Patient login QRs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["patient", "is_active"],
                        name="patients_pa_patient_32f34c_idx",
                    ),
                    models.Index(
                        fields=["is_active", "revoked_at"],
                        name="patients_pa_is_acti_0cc4a9_idx",
                    ),
                ],
            },
        ),
    ]
