# Generated by Django 5.1.15 on 2026-05-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_patientloginqr"),
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSessionQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Patient session QR",
                "verbose_name_plural": "Patient session QRs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="patientsession",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="patientsession",
            index=models.Index(
                fields=["status", "expires_at"], name="patients_pa_status_372ade_idx"
            ),
        ),
        migrations.AddField(
            model_name="patientsessionqr",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_qr_tokens",
                to="patients.patientprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="patientsessionqr",
            index=models.Index(
                fields=["patient", "used_at", "revoked_at"],
                name="patients_pa_patient_a4a22d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientsessionqr",
            index=models.Index(
                fields=["expires_at"], name="patients_pa_expires_1e9f49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientsessionqr",
            index=models.Index(
                fields=["used_at"], name="patients_pa_used_at_e3f638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientsessionqr",
            index=models.Index(
                fields=["revoked_at"], name="patients_pa_revoked_90307f_idx"
            ),
        ),
    ]
