# Generated by Django 5.1.15 on 2026-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientsessionqr_patientsession_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalinfo',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], max_length=6),
        ),
    ]
