# Generated by Django 5.1.15 on 2026-06-05 09:28

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientprofile_city_region_hearing_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalinfo',
            name='allergies',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalinfo',
            name='chronic_conditions',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalinfo',
            name='notes',
            field=common.fields.EncryptedTextField(blank=True),
        ),
    ]
