# Generated by Django 5.1.15 on 2026-06-05

from django.db import migrations


def encrypt_existing_patient_medical_info(apps, schema_editor):
    PatientMedicalInfo = apps.get_model("patients", "PatientMedicalInfo")
    encrypted_fields = ("chronic_conditions", "allergies", "notes")

    for medical_info in PatientMedicalInfo.objects.all().iterator():
        values = {
            field: getattr(medical_info, field)
            for field in encrypted_fields
            if getattr(medical_info, field)
        }
        if values:
            PatientMedicalInfo.objects.filter(pk=medical_info.pk).update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_alter_patientmedicalinfo_allergies_and_more"),
    ]

    operations = [
        migrations.RunPython(
            encrypt_existing_patient_medical_info,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
